### ISSUE TITLE
Bastet - Bastard tetris

### ISSUE THREAD

**Issue by denilsonsa** [livibetter/READYT#11]
Since you have covered many (console) Tetris clones in your channel, I believe you should give `bastet` a try.

http://fph.altervista.org/prog/bastet.html
https://github.com/fph/bastet/

> Bastet stands for "bastard tetris", and is a simple ncurses-based Tetris(R) clone for Linux. Unlike normal Tetris(R), however, Bastet does not choose your next brick at random. Instead, Bastet uses a special algorithm designed to choose the worst brick possible. As you can imagine, playing Bastet can be a very frustrating experience!

**Comment by livibetter** [comment]
[![thumb][i]][v]

[v]: https://www.youtube.com/watch?v=3NwV9IJg32k
[i]: https://i.ytimg.com/vi/3NwV9IJg32k/maxresdefault.jpg
